# This workflow will run daily at 06:45.
# It will install Python dependencies and run tests with a variety of Python versions.
# See documentation for help debugging smoke test issues:
#    https://lincc-ppt.readthedocs.io/en/latest/practices/ci_testing.html#version-culprit

name: Benchmark runtime and memory usage

on: [push]

permissions:
   contents: write
   deployments: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install .
        pip install .[dev]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run benchmarks with pytest and monitor plugin
      run: |
        pytest tests/ \
          --parametrization-explicit \
          --db benchmarks/results.db
    - name: Extract relevant metrics
      run: |
        sqlite3 benchmarks/results.db \
          '.mode json' \
          '.once benchmarks/results.json' \
          'SELECT ITEM, TOTAL_TIME, MEM_USAGE FROM TEST_METRICS'
        python benchmarks/preprocess_bench.py
    - name: Store benchmark results
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: SUPERHOT-PLUS Benchmarking Monitor
        # Using a custom benchmark strategy, where the smaller the value the better
        tool: 'customSmallerIsBetter' 
        output-file-path: benchmarks/results.json
        gh-pages-branch: gh-pages
        auto-push: false
    # Push gh-pages branch by yourself
    - name: Push benchmark result
      run: git push 'https://lincc-frameworks:${{ secrets.GITHUB_TOKEN }}@github.com/lincc-frameworks/superphot-plus.git' gh-pages:gh-pages
